[Loc]

students = Data/students.csv
courses = Data/courses.csv
enrollments = Data/enrollments.csv

[Test]

students = Data/students.csv
courses = Data/courses.csv
enrollments = Data/enrollments.csv

[Production]

students = Data/students.csv
courses = Data/courses.csv
enrollments = Data/enrollments.csv