[Loc]

spark.app.name = bigdatacourse

[Test]

spark.app.name = bigdatacourse
spark.num.executors = 3 
spark.executors.cores = 5
spark.executors.memory = 15GB

[Production]

spark.app.name = bigdatacourse
spark.num.executors = 3 
spark.executors.cores = 5
spark.executors.memory = 15GB